<?php

namespace app\admin\model;

use think\Model;

class BaseModel extends Model
{
    protected $table;
    protected $pk;
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->table=$this->getTable();
        $this->pk=$this->getPk();
    }

    //更新数据
    public function _update($data){
        if(isset($data['id'])){
            //修改
            return $this->save($data,['id'=>$data['id']]);
        }else{
            //添加
            return $this->save($data);
        }
    }
    //递归
    public function recursion($arr, $id)
    {
        $list = array();
        foreach ($arr as $k => $v) {
            if ($v['pid'] == $id) {
                $child = $this->recursion($arr, $v['id']);
                if (!empty($child)) {
                    $v['child'] = $child;
                }else{
                    $v['child'] = '';
                }
                $list[] = $v;
            }
        }
        return $list;
    }
}
