<?php

namespace app\admin\controller;

use think\Controller;

class Base extends Controller
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if(!session('aid')){
            $this->redirect(url('Login/index'));
        }
    }
}
