<?php

namespace app\api\controller;

use think\Controller;

class Base extends Controller
{
    //解决跨域
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        header("Access-Control-Allow-Origin:*");
        header("Access-Control-Allow-Methods:GET, POST, OPTIONS, DELETE");
        header("Access-Control-Allow-Headers:DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type, Accept-Language, Origin, Accept-Encoding");
    }
}
