<?php

namespace app\api\controller;

use Firebase\JWT\JWT;

class Home extends Base
{
    //验证jwt token鉴权
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $header=request()->header();
        if(!isset($header['token'])){
            return json(['code'=>0,'msg'=>'token不能为空'],400);
        }
        $token=$header['token'];
        $key='api';
        try{
            $info=JWT::decode($token, $key, array('HS256'));
        }catch(\Exception $e){
            return json(['code'=>0,'msg'=>$e->getMessage()],400)->send();
          }
        $this->uid=$info->uid;
    }
}
